Place.create(:name => "Starbucks",
             :tel => "911",
             :address => "Departure / Check-in Hall South, #026-049 Terminal 2 Singapore Changi Airport, Singapore 819643",
             :longitude => 2,
             :latitude => 3)
Place.create(:name => "KFC",
             :tel => "911",
             :address => "Departure / Check-in Hall South, #026-049 Terminal 2 Singapore Changi Airport, Singapore 819643",
             :longitude => 4,
             :latitude => 6)
Place.create(:name => "McDonald",
             :tel => "911",
             :address => "Departure / Check-in Hall South, #026-049 Terminal 2 Singapore Changi Airport, Singapore 819643",
             :longitude => 8,
             :latitude => 2)
Place.create(:name => "7/11",
             :tel => "911",
             :address => "Departure / Check-in Hall South, #026-049 Terminal 2 Singapore Changi Airport, Singapore 819643",
             :longitude => 1,
             :latitude => 0)
Place.create(:name => "Uniqlo",
             :tel => "911",
             :address => "Departure / Check-in Hall South, #026-049 Terminal 2 Singapore Changi Airport, Singapore 819643",
             :longitude => 4,
             :latitude => 5)
Place.create(:name => "Starbucks",
             :tel => "911",
             :address => "Departure / Check-in Hall South, #026-049 Terminal 2 Singapore Changi Airport, Singapore 819643",
             :longitude => 6,
             :latitude => 3)
